// Code generated by cmd/remote-protocol-gen; DO NOT EDIT.

package protocol

// GeneratedSchemaHash is the SHA-256 of schema.generated.json. Production
// Build IDs use this constant; protocol tests independently recompute it from
// CanonicalSchemaBytes to reject stale generated artifacts.
const GeneratedSchemaHash = "sha256:ddde6a7dd832f74abc411ea632cc37df807c4f5eda6161b1da114d006d5275f8"
