export const DesktopErrorCode = {
  UNTRUSTED_IPC: "VOLT_UNTRUSTED_IPC",
  DSH_NOT_STARTED: "VOLT_DSH_NOT_STARTED",
  DSH_STOPPED: "VOLT_DSH_STOPPED",
  DSH_NOT_AUTHENTICATED: "VOLT_DSH_NOT_AUTHENTICATED",
  DSH_AUTH_FAILED: "VOLT_DSH_AUTH_FAILED",
  DSH_REQUEST_FAILED: "VOLT_DSH_REQUEST_FAILED",
  DSH_RESPONSE_INVALID: "VOLT_DSH_RESPONSE_INVALID",
  DSH_METHOD_DENIED: "VOLT_DSH_METHOD_DENIED",
  DSH_METHOD_UNSUPPORTED: "VOLT_DSH_METHOD_UNSUPPORTED",
  DSH_METHOD_INVALID: "VOLT_DSH_METHOD_INVALID",
  DSH_FOLLOW_REPLACED: "VOLT_DSH_FOLLOW_REPLACED",
  DSH_FOLLOW_EMPTY: "VOLT_DSH_FOLLOW_EMPTY",
  DSH_STREAM_EMPTY: "VOLT_DSH_STREAM_EMPTY",
  DSH_STREAM_NOT_READY: "VOLT_DSH_STREAM_NOT_READY",
  DSH_EXPORT_FAILED: "VOLT_DSH_EXPORT_FAILED",
  DSH_START_URL_INVALID: "VOLT_DSH_START_URL_INVALID",
  DSH_STARTUP_FAILED: "VOLT_DSH_STARTUP_FAILED",
  EXTERNAL_URL_INVALID: "VOLT_EXTERNAL_URL_INVALID",
  EXTERNAL_URL_DENIED: "VOLT_EXTERNAL_URL_DENIED",
  SESSION_ID_INVALID: "VOLT_SESSION_ID_INVALID",
  CREDENTIAL_PROVISION_FAILED: "VOLT_CREDENTIAL_PROVISION_FAILED",
  BUNDLED_ENDPOINT_INVALID: "VOLT_BUNDLED_ENDPOINT_INVALID",
  BUNDLED_CREDENTIAL_INVALID: "VOLT_BUNDLED_CREDENTIAL_INVALID",
  BUNDLED_CREDENTIAL_OVERRIDDEN: "VOLT_BUNDLED_CREDENTIAL_OVERRIDDEN",
  SMB_INVALID_ID: "VOLT_SMB_INVALID_ID",
  SMB_INVALID_DRIVE: "VOLT_SMB_INVALID_DRIVE",
  SMB_INVALID_UNC: "VOLT_SMB_INVALID_UNC",
  SMB_INVALID_REQUEST: "VOLT_SMB_INVALID_REQUEST",
  SMB_MISSING: "VOLT_SMB_MISSING",
  SMB_NOT_MOUNTED: "VOLT_SMB_NOT_MOUNTED",
  SMB_MAPPED_ELSEWHERE: "VOLT_SMB_MAPPED_ELSEWHERE",
  SMB_INVALID_DISPLAY_NAME: "VOLT_SMB_INVALID_DISPLAY_NAME",
  SMB_UNSUPPORTED_OPEN: "VOLT_SMB_UNSUPPORTED_OPEN",
  SMB_OPERATION_FAILED: "VOLT_SMB_OPERATION_FAILED",
} as const;

export type DesktopErrorCode = (typeof DesktopErrorCode)[keyof typeof DesktopErrorCode];

export function desktopErrorMessage(code: string, detail?: string): string {
  return detail ? `${code}: ${detail}` : code;
}

export function desktopError(code: string, detail?: string, options?: ErrorOptions): Error {
  return new Error(desktopErrorMessage(code, detail), options);
}

export function parseDesktopErrorCode(message: string): DesktopErrorCode | undefined {
  const match = message.trim().match(/^(VOLT_[A-Z0-9_]+)/u);
  if (!match) return undefined;
  return (Object.values(DesktopErrorCode) as string[]).includes(match[1] ?? "")
    ? match[1] as DesktopErrorCode
    : undefined;
}
