// Package protocolgen generates every committed Remote protocol artifact from
// the frozen Go wire registry and its canonical schema document.
package protocolgen

import (
	"bytes"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"reflect"
	"sort"

	"reasonix/internal/remote/protocol"
)

const (
	SchemaArtifactPath     = "internal/remote/protocol/schema.generated.json"
	SchemaHashArtifactPath = "internal/remote/protocol/schema_hash.generated.go"
	TypeScriptArtifactPath = "desktop/frontend/src/generated/remoteProtocol.generated.ts"
)

// Artifact is one deterministic generated file, relative to the repository
// root. Artifacts are always returned in the stable order declared above.
type Artifact struct {
	Path string
	Data []byte
}

type methodBinding struct {
	Method     protocol.SchemaMethod
	ParamsName string
	ResultName string
}

type namedSchema struct {
	Name   string
	Schema protocol.SchemaType
}

// Generate builds all Remote protocol artifacts without reading the committed
// outputs. The schema hash is calculated from the exact JSON bytes returned as
// the schema artifact.
func Generate() ([]Artifact, error) {
	if err := protocol.ValidateRegistry(); err != nil {
		return nil, fmt.Errorf("validate registry: %w", err)
	}
	document, err := protocol.BuildSchemaDocument()
	if err != nil {
		return nil, fmt.Errorf("build schema: %w", err)
	}
	canonical, err := protocol.CanonicalSchemaBytes()
	if err != nil {
		return nil, fmt.Errorf("canonical schema: %w", err)
	}
	encoded, err := json.Marshal(document)
	if err != nil {
		return nil, fmt.Errorf("marshal schema document: %w", err)
	}
	if !bytes.Equal(canonical, encoded) {
		return nil, fmt.Errorf("canonical schema bytes do not match BuildSchemaDocument")
	}

	bindings, names, err := bindRegistry(document)
	if err != nil {
		return nil, err
	}
	digest := sha256.Sum256(canonical)
	schemaHash := "sha256:" + hex.EncodeToString(digest[:])
	hashSource, err := generateSchemaHashGo(schemaHash)
	if err != nil {
		return nil, err
	}
	typeScript, err := generateTypeScript(document, bindings, names, schemaHash)
	if err != nil {
		return nil, fmt.Errorf("generate TypeScript: %w", err)
	}

	return []Artifact{
		{Path: SchemaArtifactPath, Data: append([]byte(nil), canonical...)},
		{Path: SchemaHashArtifactPath, Data: hashSource},
		{Path: TypeScriptArtifactPath, Data: typeScript},
	}, nil
}

func bindRegistry(document protocol.SchemaDocument) ([]methodBinding, []namedSchema, error) {
	registry := protocol.Registry()
	if len(document.Methods) != len(registry) {
		return nil, nil, fmt.Errorf("schema has %d methods, registry has %d", len(document.Methods), len(registry))
	}

	bindings := make([]methodBinding, 0, len(document.Methods))
	byName := make(map[string]protocol.SchemaType, len(document.Methods)*2)
	for i, method := range document.Methods {
		if i > 0 && document.Methods[i-1].Name >= method.Name {
			return nil, nil, fmt.Errorf("schema methods are not strictly sorted at %q", method.Name)
		}
		spec := registry[i]
		if method.Name != spec.Name || method.Direction != spec.Direction || method.Class != spec.Class {
			return nil, nil, fmt.Errorf("schema method metadata for %q does not match registry", method.Name)
		}
		paramsName := spec.ParamsType.Name()
		resultName := spec.ResultType.Name()
		if paramsName == "" || resultName == "" {
			return nil, nil, fmt.Errorf("method %q uses an unnamed wire type", method.Name)
		}
		if err := addNamedSchema(byName, paramsName, method.Params); err != nil {
			return nil, nil, fmt.Errorf("method %q params: %w", method.Name, err)
		}
		// Requests (either direction) publish result schemas; notifications do not.
		if method.Direction == protocol.DirectionClientRequest || method.Direction == protocol.DirectionHostRequest {
			if err := addNamedSchema(byName, resultName, method.Result); err != nil {
				return nil, nil, fmt.Errorf("method %q result: %w", method.Name, err)
			}
		}
		bindings = append(bindings, methodBinding{Method: method, ParamsName: paramsName, ResultName: resultName})
	}

	names := make([]string, 0, len(byName))
	for name := range byName {
		names = append(names, name)
	}
	sort.Strings(names)
	named := make([]namedSchema, 0, len(names))
	for _, name := range names {
		named = append(named, namedSchema{Name: name, Schema: byName[name]})
	}
	return bindings, named, nil
}

func addNamedSchema(schemas map[string]protocol.SchemaType, name string, schema protocol.SchemaType) error {
	if existing, ok := schemas[name]; ok {
		if !reflect.DeepEqual(existing, schema) {
			return fmt.Errorf("wire type %s has conflicting schemas", name)
		}
		return nil
	}
	schemas[name] = schema
	return nil
}

func generateSchemaHashGo(schemaHash string) ([]byte, error) {
	source := fmt.Sprintf(`// Code generated by cmd/remote-protocol-gen; DO NOT EDIT.

package protocol

// GeneratedSchemaHash is the SHA-256 of schema.generated.json. Production
// Build IDs use this constant; protocol tests independently recompute it from
// CanonicalSchemaBytes to reject stale generated artifacts.
const GeneratedSchemaHash = %q
`, schemaHash)
	formatted, err := format.Source([]byte(source))
	if err != nil {
		return nil, fmt.Errorf("format schema hash source: %w", err)
	}
	return formatted, nil
}

// Write writes a generated artifact set below root.
func Write(root string, artifacts []Artifact) error {
	for _, artifact := range artifacts {
		path := filepath.Join(root, filepath.FromSlash(artifact.Path))
		if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
			return fmt.Errorf("create directory for %s: %w", artifact.Path, err)
		}
		if err := os.WriteFile(path, artifact.Data, 0o644); err != nil {
			return fmt.Errorf("write %s: %w", artifact.Path, err)
		}
	}
	return nil
}

// Check compares a generated artifact set byte-for-byte with files below root.
func Check(root string, artifacts []Artifact) error {
	for _, artifact := range artifacts {
		path := filepath.Join(root, filepath.FromSlash(artifact.Path))
		committed, err := os.ReadFile(path)
		if err != nil {
			return fmt.Errorf("read %s: %w", artifact.Path, err)
		}
		if !bytes.Equal(committed, artifact.Data) {
			return fmt.Errorf("generated artifact drift: %s", artifact.Path)
		}
	}
	return nil
}
