package protocolgen

import (
	"bytes"
	"encoding/json"
	"fmt"
	"sort"
	"strconv"
	"strings"

	"reasonix/internal/remote/protocol"
)

type hydrationMode uint8

const (
	rawMode hydrationMode = iota
	hydratedMode
)

type tsRenderer struct{}

func generateTypeScript(document protocol.SchemaDocument, bindings []methodBinding, names []namedSchema, schemaHash string) ([]byte, error) {
	initialize, err := findMethod(document, protocol.MethodRemoteInitialize)
	if err != nil {
		return nil, err
	}
	buildID, err := findProperty(initialize.Params, "buildId")
	if err != nil {
		return nil, fmt.Errorf("initialize build ID: %w", err)
	}
	capabilities, err := findProperty(initialize.Result, "capabilities")
	if err != nil {
		return nil, fmt.Errorf("initialize capabilities: %w", err)
	}
	capabilitySchema, err := specializeCapabilities(capabilities.Schema, document)
	if err != nil {
		return nil, err
	}
	reasonixCode, err := findProperty(document.ErrorData, "reasonixCode")
	if err != nil {
		return nil, err
	}
	action, err := findProperty(document.ErrorData, "action")
	if err != nil {
		return nil, err
	}
	eventSchema, err := specializeEvent(document.Event)
	if err != nil {
		return nil, err
	}

	renderer := tsRenderer{}
	var out bytes.Buffer
	out.WriteString("// Code generated by cmd/remote-protocol-gen; DO NOT EDIT.\n\n")
	writeTSConst(&out, "REMOTE_SCHEMA_FORMAT", document.Format)
	writeTSConst(&out, "REMOTE_PROTOCOL_VERSION", document.ProtocolVersion)
	writeTSConst(&out, "REMOTE_SCHEMA_HASH", schemaHash)
	out.WriteByte('\n')

	resources, err := json.MarshalIndent(document.Resources, "", "  ")
	if err != nil {
		return nil, err
	}
	fmt.Fprintf(&out, "export const REMOTE_FIXED_RESOURCES = %s as const;\n\n", resources)
	writeStringArrayConst(&out, "REMOTE_REQUIRED_FEATURES", document.Features.RequiredTrue)
	writeStringArrayConst(&out, "REMOTE_DYNAMIC_FEATURES", document.Features.Dynamic)
	writeStringArrayConst(&out, "REMOTE_DEFERRED_FEATURES", document.Features.RequiredFalse)
	out.WriteString("export type RemoteRequiredFeature = (typeof REMOTE_REQUIRED_FEATURES)[number];\n")
	out.WriteString("export type RemoteDynamicFeature = (typeof REMOTE_DYNAMIC_FEATURES)[number];\n")
	out.WriteString("export type RemoteDeferredFeature = (typeof REMOTE_DEFERRED_FEATURES)[number];\n")
	out.WriteString("export type RemoteFeatureName = RemoteRequiredFeature | RemoteDynamicFeature | RemoteDeferredFeature;\n\n")
	out.WriteString("export type RemoteJSONValue = null | boolean | number | string | Array<RemoteJSONValue> | { [key: string]: RemoteJSONValue };\n\n")

	if err := writePair(&out, renderer, "RemoteBuildID", buildID.Schema); err != nil {
		return nil, err
	}
	if err := writePair(&out, renderer, "RemoteCapabilities", capabilitySchema); err != nil {
		return nil, err
	}
	writeStringArrayConst(&out, "REMOTE_EVENT_KINDS", document.Event.Kinds)
	writeStringArrayConst(&out, "REMOTE_EVENT_EXTERNALIZABLE_JSON_POINTERS", document.Event.ExternalizableJSONPointers)
	out.WriteString("export type RemoteEventKind = (typeof REMOTE_EVENT_KINDS)[number];\n")
	if err := writePair(&out, renderer, "RemoteEvent", eventSchema); err != nil {
		return nil, err
	}
	if err := writeSchemaAlias(&out, renderer, "ReasonixErrorCode", reasonixCode.Schema, hydratedMode); err != nil {
		return nil, err
	}
	if err := writeSchemaAlias(&out, renderer, "RemoteAction", action.Schema, hydratedMode); err != nil {
		return nil, err
	}
	if err := writePair(&out, renderer, "RemoteErrorData", document.ErrorData); err != nil {
		return nil, err
	}
	errorsJSON, err := json.MarshalIndent(document.Errors, "", "  ")
	if err != nil {
		return nil, err
	}
	fmt.Fprintf(&out, "export const REMOTE_ERROR_CONTRACTS = %s as const;\n", errorsJSON)
	out.WriteString("export type RemoteErrorContract = (typeof REMOTE_ERROR_CONTRACTS)[number];\n\n")

	for _, named := range names {
		if err := writePair(&out, renderer, named.Name, named.Schema); err != nil {
			return nil, fmt.Errorf("render %s: %w", named.Name, err)
		}
	}
	writeMethodMetadata(&out, bindings)
	writeMethodMaps(&out, bindings)

	return out.Bytes(), nil
}

func writeTSConst(out *bytes.Buffer, name, value string) {
	fmt.Fprintf(out, "export const %s = %s as const;\n", name, quoteTS(value))
}

func writeStringArrayConst(out *bytes.Buffer, name string, values []string) {
	fmt.Fprintf(out, "export const %s = [", name)
	for i, value := range values {
		if i > 0 {
			out.WriteString(", ")
		}
		out.WriteString(quoteTS(value))
	}
	out.WriteString("] as const;\n")
}

func writePair(out *bytes.Buffer, renderer tsRenderer, name string, schema protocol.SchemaType) error {
	if err := writeSchemaAlias(out, renderer, name+"Raw", schema, rawMode); err != nil {
		return err
	}
	if err := writeSchemaAlias(out, renderer, name+"Hydrated", schema, hydratedMode); err != nil {
		return err
	}
	out.WriteByte('\n')
	return nil
}

func writeSchemaAlias(out *bytes.Buffer, renderer tsRenderer, name string, schema protocol.SchemaType, mode hydrationMode) error {
	value, err := renderer.render(schema, mode, false, 0)
	if err != nil {
		return err
	}
	fmt.Fprintf(out, "export type %s = %s;\n", name, value)
	return nil
}

func writeMethodMetadata(out *bytes.Buffer, bindings []methodBinding) {
	out.WriteString("export const REMOTE_METHODS = [\n")
	for _, binding := range bindings {
		fmt.Fprintf(out, "  { method: %s, direction: %s, class: %s },\n",
			quoteTS(string(binding.Method.Name)), quoteTS(string(binding.Method.Direction)), quoteTS(string(binding.Method.Class)))
	}
	out.WriteString("] as const;\n")
	out.WriteString("export type RemoteMethodMetadata = (typeof REMOTE_METHODS)[number];\n")
	out.WriteString("export type RemoteOperationClass = RemoteMethodMetadata[\"class\"];\n\n")
}

func writeMethodMaps(out *bytes.Buffer, bindings []methodBinding) {
	writeMap := func(name string, direction protocol.Direction, selector func(methodBinding) string) {
		fmt.Fprintf(out, "export interface %s {\n", name)
		for _, binding := range bindings {
			if binding.Method.Direction != direction {
				continue
			}
			fmt.Fprintf(out, "  %s: %s;\n", quoteTS(string(binding.Method.Name)), selector(binding))
		}
		out.WriteString("}\n\n")
	}
	writeMap("RemoteRequestParamsRawByMethod", protocol.DirectionClientRequest, func(binding methodBinding) string { return binding.ParamsName + "Raw" })
	writeMap("RemoteRequestParamsHydratedByMethod", protocol.DirectionClientRequest, func(binding methodBinding) string { return binding.ParamsName + "Hydrated" })
	writeMap("RemoteRequestResultRawByMethod", protocol.DirectionClientRequest, func(binding methodBinding) string { return binding.ResultName + "Raw" })
	writeMap("RemoteRequestResultHydratedByMethod", protocol.DirectionClientRequest, func(binding methodBinding) string { return binding.ResultName + "Hydrated" })
	writeMap("RemoteNotificationParamsRawByMethod", protocol.DirectionHostNotification, func(binding methodBinding) string { return binding.ParamsName + "Raw" })
	writeMap("RemoteNotificationParamsHydratedByMethod", protocol.DirectionHostNotification, func(binding methodBinding) string { return binding.ParamsName + "Hydrated" })
	// Provider Broker directions (Host → Desktop requests; Desktop → Host notifications).
	writeMap("BrokerRequestParamsRawByMethod", protocol.DirectionHostRequest, func(binding methodBinding) string { return binding.ParamsName + "Raw" })
	writeMap("BrokerRequestParamsHydratedByMethod", protocol.DirectionHostRequest, func(binding methodBinding) string { return binding.ParamsName + "Hydrated" })
	writeMap("BrokerRequestResultRawByMethod", protocol.DirectionHostRequest, func(binding methodBinding) string { return binding.ResultName + "Raw" })
	writeMap("BrokerRequestResultHydratedByMethod", protocol.DirectionHostRequest, func(binding methodBinding) string { return binding.ResultName + "Hydrated" })
	writeMap("BrokerNotificationParamsRawByMethod", protocol.DirectionClientNotification, func(binding methodBinding) string { return binding.ParamsName + "Raw" })
	writeMap("BrokerNotificationParamsHydratedByMethod", protocol.DirectionClientNotification, func(binding methodBinding) string { return binding.ParamsName + "Hydrated" })

	out.WriteString("export type RemoteRequestMethod = keyof RemoteRequestParamsRawByMethod;\n")
	out.WriteString("export type RemoteNotificationMethod = keyof RemoteNotificationParamsRawByMethod;\n")
	out.WriteString("export type BrokerRequestMethod = keyof BrokerRequestParamsRawByMethod;\n")
	out.WriteString("export type BrokerNotificationMethod = keyof BrokerNotificationParamsRawByMethod;\n")
	out.WriteString("export type RemoteMethod = RemoteRequestMethod | RemoteNotificationMethod | BrokerRequestMethod | BrokerNotificationMethod;\n")
	out.WriteString("export type RemoteRequestParamsRaw<M extends RemoteRequestMethod> = RemoteRequestParamsRawByMethod[M];\n")
	out.WriteString("export type RemoteRequestParamsHydrated<M extends RemoteRequestMethod> = RemoteRequestParamsHydratedByMethod[M];\n")
	out.WriteString("export type RemoteRequestResultRaw<M extends RemoteRequestMethod> = RemoteRequestResultRawByMethod[M];\n")
	out.WriteString("export type RemoteRequestResultHydrated<M extends RemoteRequestMethod> = RemoteRequestResultHydratedByMethod[M];\n")
	out.WriteString("export type RemoteNotificationParamsRaw<M extends RemoteNotificationMethod> = RemoteNotificationParamsRawByMethod[M];\n")
	out.WriteString("export type RemoteNotificationParamsHydrated<M extends RemoteNotificationMethod> = RemoteNotificationParamsHydratedByMethod[M];\n")
}

func findMethod(document protocol.SchemaDocument, name protocol.Method) (protocol.SchemaMethod, error) {
	for _, method := range document.Methods {
		if method.Name == name {
			return method, nil
		}
	}
	return protocol.SchemaMethod{}, fmt.Errorf("method %q is missing from schema", name)
}

func findProperty(schema protocol.SchemaType, name string) (protocol.SchemaProperty, error) {
	for _, property := range schema.Properties {
		if property.Name == name {
			return property, nil
		}
	}
	return protocol.SchemaProperty{}, fmt.Errorf("property %q is missing from schema", name)
}

func specializeEvent(event protocol.EventSchema) (protocol.SchemaType, error) {
	payload, err := cloneSchema(event.Payload)
	if err != nil {
		return protocol.SchemaType{}, err
	}
	for i := range payload.Properties {
		if payload.Properties[i].Name == "kind" {
			payload.Properties[i].Schema.Enum = append([]string(nil), event.Kinds...)
			return payload, nil
		}
	}
	return protocol.SchemaType{}, fmt.Errorf("event payload does not contain kind")
}

func specializeCapabilities(schema protocol.SchemaType, document protocol.SchemaDocument) (protocol.SchemaType, error) {
	capabilities, err := cloneSchema(schema)
	if err != nil {
		return protocol.SchemaType{}, err
	}
	featuresProperty := propertyPointer(&capabilities, "features")
	limitsProperty := propertyPointer(&capabilities, "limits")
	if featuresProperty == nil || limitsProperty == nil {
		return protocol.SchemaType{}, fmt.Errorf("capabilities schema is missing features or limits")
	}

	required := stringSet(document.Features.RequiredTrue)
	dynamic := stringSet(document.Features.Dynamic)
	deferred := stringSet(document.Features.RequiredFalse)
	for i := range featuresProperty.Schema.Properties {
		property := &featuresProperty.Schema.Properties[i]
		switch {
		case required[property.Name]:
			property.Schema.Constraints = appendConstraint(property.Schema.Constraints, "true")
		case dynamic[property.Name]:
		case deferred[property.Name]:
			property.Schema.Constraints = appendConstraint(property.Schema.Constraints, "false")
		default:
			return protocol.SchemaType{}, fmt.Errorf("capability feature %q is not classified", property.Name)
		}
	}

	encodedLimits, err := json.Marshal(document.Resources.Protocol)
	if err != nil {
		return protocol.SchemaType{}, err
	}
	var limitValues map[string]json.Number
	decoder := json.NewDecoder(bytes.NewReader(encodedLimits))
	decoder.UseNumber()
	if err := decoder.Decode(&limitValues); err != nil {
		return protocol.SchemaType{}, err
	}
	for i := range limitsProperty.Schema.Properties {
		property := &limitsProperty.Schema.Properties[i]
		value, ok := limitValues[property.Name]
		if !ok {
			return protocol.SchemaType{}, fmt.Errorf("capability limit %q is not frozen", property.Name)
		}
		property.Schema.Constraints = appendConstraint(property.Schema.Constraints, "const="+value.String())
		delete(limitValues, property.Name)
	}
	if len(limitValues) != 0 {
		return protocol.SchemaType{}, fmt.Errorf("frozen protocol limits are not represented by capabilities")
	}
	return capabilities, nil
}

func propertyPointer(schema *protocol.SchemaType, name string) *protocol.SchemaProperty {
	for i := range schema.Properties {
		if schema.Properties[i].Name == name {
			return &schema.Properties[i]
		}
	}
	return nil
}

func cloneSchema(schema protocol.SchemaType) (protocol.SchemaType, error) {
	encoded, err := json.Marshal(schema)
	if err != nil {
		return protocol.SchemaType{}, err
	}
	var clone protocol.SchemaType
	if err := json.Unmarshal(encoded, &clone); err != nil {
		return protocol.SchemaType{}, err
	}
	return clone, nil
}

func stringSet(values []string) map[string]bool {
	result := make(map[string]bool, len(values))
	for _, value := range values {
		result[value] = true
	}
	return result
}

func appendConstraint(constraints []string, value string) []string {
	constraints = append(constraints, value)
	sort.Strings(constraints)
	return constraints
}

func (tsRenderer) render(schema protocol.SchemaType, mode hydrationMode, stripNullable bool, level int) (string, error) {
	var value string
	if literal, ok, err := schemaLiteral(schema); err != nil {
		return "", err
	} else if ok {
		value = literal
	} else {
		switch schema.Type {
		case "string":
			if len(schema.Enum) > 0 {
				values := make([]string, len(schema.Enum))
				for i, enumValue := range schema.Enum {
					values[i] = quoteTS(enumValue)
				}
				value = strings.Join(values, " | ")
			} else {
				value = "string"
			}
		case "boolean":
			value = "boolean"
		case "integer", "number":
			value = "number"
		case "json":
			value = "RemoteJSONValue"
		case "array":
			if schema.Items == nil {
				return "", fmt.Errorf("array schema is missing items")
			}
			item, err := (tsRenderer{}).render(*schema.Items, mode, false, level)
			if err != nil {
				return "", err
			}
			value = "Array<" + item + ">"
		case "object":
			object, err := (tsRenderer{}).renderObject(schema, mode, level)
			if err != nil {
				return "", err
			}
			value = object
		default:
			return "", fmt.Errorf("unsupported schema type %q", schema.Type)
		}
	}
	if schema.Nullable && !stripNullable {
		if strings.Contains(value, "\n") || strings.Contains(value, " | ") || strings.Contains(value, " & ") {
			value = "(" + value + ")"
		}
		value += " | null"
	}
	return value, nil
}

func (r tsRenderer) renderObject(schema protocol.SchemaType, mode hydrationMode, level int) (string, error) {
	base := schema
	base.Validation = nil
	baseValue, err := r.renderObjectBase(base, mode, level)
	if err != nil {
		return "", err
	}
	if schema.Validation == nil || schema.Validation.Discriminator == nil {
		return baseValue, nil
	}
	discriminator := schema.Validation.Discriminator
	if len(discriminator.Variants) == 0 {
		return "", fmt.Errorf("discriminator %q has no variants", discriminator.Property)
	}
	if err := validateDiscriminator(schema, *discriminator); err != nil {
		return "", err
	}
	variants := make([]string, 0, len(discriminator.Variants))
	for _, variant := range discriminator.Variants {
		value, err := r.renderVariant(schema, *discriminator, variant, mode, level+1)
		if err != nil {
			return "", err
		}
		variants = append(variants, value)
	}
	separator := "\n" + indent(level+1) + "| "
	return "(" + baseValue + ") & (\n" + indent(level+1) + strings.Join(variants, separator) + "\n" + indent(level) + ")", nil
}

func (r tsRenderer) renderObjectBase(schema protocol.SchemaType, mode hydrationMode, level int) (string, error) {
	if len(schema.Properties) == 0 {
		if schema.AdditionalProperties == nil {
			return "Record<string, never>", nil
		}
		additional, err := r.render(*schema.AdditionalProperties, mode, false, level)
		if err != nil {
			return "", err
		}
		return "Record<string, " + additional + ">", nil
	}

	var out strings.Builder
	out.WriteString("{\n")
	for _, property := range schema.Properties {
		value, err := r.render(property.Schema, mode, mode == hydratedMode && property.Externalizable, level+1)
		if err != nil {
			return "", fmt.Errorf("property %s: %w", property.Name, err)
		}
		out.WriteString(indent(level + 1))
		out.WriteString(quoteTS(property.Name))
		if !property.Required {
			out.WriteByte('?')
		}
		out.WriteString(": ")
		out.WriteString(value)
		out.WriteString(";\n")
	}
	out.WriteString(indent(level))
	out.WriteByte('}')
	value := out.String()
	if schema.AdditionalProperties != nil {
		additional, err := r.render(*schema.AdditionalProperties, mode, false, level)
		if err != nil {
			return "", err
		}
		value = "(" + value + ") & Record<string, " + additional + ">"
	}
	return value, nil
}

func (r tsRenderer) renderVariant(schema protocol.SchemaType, discriminator protocol.SchemaDiscriminator, variant protocol.SchemaVariant, mode hydrationMode, level int) (string, error) {
	if len(variant.Values) == 0 {
		return "", fmt.Errorf("discriminator %q contains a variant without values", discriminator.Property)
	}
	required := stringSet(variant.Required)
	forbidden := stringSet(variant.Forbidden)
	requiredTrue := stringSet(variant.RequiredTrue)
	requiredFalse := stringSet(variant.RequiredFalse)
	if required[discriminator.Property] || forbidden[discriminator.Property] || requiredTrue[discriminator.Property] || requiredFalse[discriminator.Property] {
		return "", fmt.Errorf("discriminator %q must not also be a variant field constraint", discriminator.Property)
	}

	known := make(map[string]protocol.SchemaProperty, len(schema.Properties))
	for _, property := range schema.Properties {
		known[property.Name] = property
	}
	for _, fields := range []map[string]bool{required, forbidden, requiredTrue, requiredFalse} {
		for name := range fields {
			if _, ok := known[name]; !ok {
				return "", fmt.Errorf("variant references unknown property %q", name)
			}
		}
	}
	for name := range required {
		if forbidden[name] || requiredTrue[name] || requiredFalse[name] {
			return "", fmt.Errorf("variant has conflicting constraints for %q", name)
		}
	}
	for name := range forbidden {
		if requiredTrue[name] || requiredFalse[name] {
			return "", fmt.Errorf("variant has conflicting constraints for %q", name)
		}
		if known[name].Required {
			return "", fmt.Errorf("variant forbids globally required property %q", name)
		}
	}
	for name := range requiredTrue {
		if requiredFalse[name] || known[name].Schema.Type != "boolean" {
			return "", fmt.Errorf("variant has invalid boolean constraint for %q", name)
		}
	}
	for name := range requiredFalse {
		if known[name].Schema.Type != "boolean" {
			return "", fmt.Errorf("variant has invalid boolean constraint for %q", name)
		}
	}

	var out strings.Builder
	out.WriteString("{\n")
	for _, property := range schema.Properties {
		var value string
		var include, optional bool
		switch {
		case property.Name == discriminator.Property:
			values := make([]string, len(variant.Values))
			for i, item := range variant.Values {
				values[i] = quoteTS(item)
			}
			value, include = strings.Join(values, " | "), true
		case forbidden[property.Name]:
			value, include, optional = "never", true, true
		case requiredTrue[property.Name]:
			value, include = "true", true
		case requiredFalse[property.Name]:
			value, include = "false", true
		case required[property.Name]:
			var err error
			value, err = r.render(property.Schema, mode, mode == hydratedMode && property.Externalizable, level+1)
			if err != nil {
				return "", err
			}
			include = true
		}
		if !include {
			continue
		}
		out.WriteString(indent(level + 1))
		out.WriteString(quoteTS(property.Name))
		if optional {
			out.WriteByte('?')
		}
		out.WriteString(": ")
		out.WriteString(value)
		out.WriteString(";\n")
	}
	out.WriteString(indent(level))
	out.WriteByte('}')
	return out.String(), nil
}

func validateDiscriminator(schema protocol.SchemaType, discriminator protocol.SchemaDiscriminator) error {
	property, err := findProperty(schema, discriminator.Property)
	if err != nil {
		return fmt.Errorf("discriminator: %w", err)
	}
	if !property.Required || property.Schema.Type != "string" {
		return fmt.Errorf("discriminator property %q must be a required string", discriminator.Property)
	}
	allowed := stringSet(property.Schema.Enum)
	seen := make(map[string]bool, len(allowed))
	for _, variant := range discriminator.Variants {
		for _, value := range variant.Values {
			if len(allowed) > 0 && !allowed[value] {
				return fmt.Errorf("discriminator %q has unknown value %q", discriminator.Property, value)
			}
			if seen[value] {
				return fmt.Errorf("discriminator %q repeats value %q", discriminator.Property, value)
			}
			seen[value] = true
		}
	}
	for value := range allowed {
		if !seen[value] {
			return fmt.Errorf("discriminator %q does not cover value %q", discriminator.Property, value)
		}
	}
	return nil
}

func schemaLiteral(schema protocol.SchemaType) (string, bool, error) {
	var literal string
	found := false
	for _, constraint := range schema.Constraints {
		value := ""
		switch {
		case strings.HasPrefix(constraint, "const="):
			value = strings.TrimPrefix(constraint, "const=")
		case schema.Type == "boolean" && (constraint == "true" || constraint == "false"):
			value = constraint
		default:
			continue
		}
		var rendered string
		switch schema.Type {
		case "string":
			rendered = quoteTS(value)
		case "boolean":
			if value != "true" && value != "false" {
				return "", false, fmt.Errorf("invalid boolean constant %q", value)
			}
			rendered = value
		case "integer":
			if _, err := strconv.ParseInt(value, 10, 64); err != nil {
				return "", false, fmt.Errorf("invalid integer constant %q", value)
			}
			rendered = value
		case "number":
			if _, err := strconv.ParseFloat(value, 64); err != nil {
				return "", false, fmt.Errorf("invalid number constant %q", value)
			}
			rendered = value
		default:
			return "", false, fmt.Errorf("constant constraint on %q schema", schema.Type)
		}
		if found && rendered != literal {
			return "", false, fmt.Errorf("conflicting constant constraints %s and %s", literal, rendered)
		}
		literal, found = rendered, true
	}
	return literal, found, nil
}

func indent(level int) string {
	if level <= 0 {
		return ""
	}
	return strings.Repeat("  ", level)
}

func quoteTS(value string) string {
	encoded, err := json.Marshal(value)
	if err != nil {
		panic(err)
	}
	return string(encoded)
}
